### PR TITLE
[JENKINS-26056] Pipeline-compatible Ant build wrapper

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-26056](https://issues.jenkins-ci.org/browse/JENKINS-26056)

Subsumes #29.

Analogous to https://github.com/jenkinsci/gradle-plugin/pull/52.

```groovy
node {
    git 'https://git-wip-us.apache.org/repos/asf/ant.git'
    withAnt {
        sh './build.sh'
    }
}
```

screenshot

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Seems like `AntTargetNote` detection randomly fails on this CI server. Cannot reproduce locally, and seems to happen sometimes in the freestyle builder too.

**Comment by rsandell** [comment]
:bee:

**Comment by recampbell** [comment]
@jglick What is the next step? Anything you need help with?

**Comment by jglick** [comment]
> will be a bit confusing for Freestyle users ("Why is there a wrapper for Ant?")

OTOH it means you can do something in a freestyle project which you could not do before. Consider the freestyle equivalent of the sample Pipeline script mentioned in the PR description.

**Comment by jglick** [comment]
@reviewbybees done

@armfergom are you maintaining this plugin?

CC @alexbrjo working on a similar patch

**Pull request merged**
