### PR TITLE
[JENKINS-33727] Integrating and fixing #14

### PR DESCRIPTION
**Pull request by armfergom**
[JENKINS-33727](https://issues.jenkins-ci.org/browse/JENKINS-33727)

Supersedes #14 
Integrate with changes in master and removing unneeded single quotes. 

Reproduced issue. Built plugin and tested in:

Windows:
- Jenkins 1.642.4. Works with and without the fix included in this PR (as expected).
- Jenkins 1.651.1.  Works with and without the fix included in this PR (as expected).
- Jenkins 1.652.  Works with and without the fix included in this PR (as expected).

Problem is detected from 1.653 onwards:
- Jenkins 1.653. The PR fixes the problem. 
- Jenkins 2.1. The PR fixes the problem.

Also tested it in Mac for versions 1.596.1 and 2.1. Issue was never present in this OS though.

@reviewbybees esp. @escoem

### CODE REVIEW

**Comment by armfergom** [comment]
@escoem would you be able to review this please?

**Comment by escoem** [comment]
👍  🐝  LGFM

**Comment by andresrc** [comment]
:bee: as far as I get it 😄

**Comment by armfergom** [comment]
@reviewbybees done

**Pull request merged**
