### PR TITLE
add ability to set build file path from beyond workspace

### PR DESCRIPTION
**Pull request by fugi**
This change adds ability to set build file path from beyond workspace.

### CODE REVIEW

**Comment by daniel-beck** [comment]
A clean PR without unnecessary changes is generally preferable.

**Comment by armfergom** [comment]
Hi @fugi ,

First of all, thanks for this PR. I have recently taken over maintainership of this plugin and I am going through open PRs. I've noticed this has been open for a while, but if you are still willing to get this merged, I am happy to start a discussion on it. 

First thing, since this is a bit old, it has conflicts with the master branch. Please, resolve them to keep going. Also, after a first look at the code, it looks good to me (have not tested it yet because of merge problems), but if we are adding the ability to specify absolute paths for the build file, it would be good to add this to the inline help for the field (`help-buildFile.html`)

Thanks,
Armando

**Comment by fugi** [comment]
Yes, I still need this.

I'm not sure about one exception. Is this
`throw new AbortException("Workspace is not available. Agent may be disconnected.");`
needed only when build file is in workspace or in all cases?

**Comment by armfergom** [comment]
Hi @fugi ,

Returning `false` is deprecated. Now, instead of returning `false`, `AbortException` must be thrown. I am not sure I follow your question. The exception is thrown if the workspace is not available.

Cheers,
Armando

**Comment by fugi** [comment]
Hi @armfergom,

I resolved  all conflicts.

**Comment by jglick** [comment]
Abandoned?

**Pull request closed without merging**
