### PR TITLE
[JENKINS-34623] Better test coverage for basic use cases

### PR DESCRIPTION
**Pull request by armfergom**
This is a downstream of #15 

Improve test coverage for plugin basic use cases.

The changes included in this PR are [here](https://github.com/jenkinsci/ant-plugin/commit/bb7057f6c3c710187be85aed0f91e33531bcd46b).

Test cases included:

- `invokeCustomTargetTest`: Invoke an Ant target that is not the default one. 
- `invokeDefaultTargetTest`: Don't specify target to invoke. Default should be used.
- `jenkinsEnvVarsFromBuildScriptTest`: Properties can be used from build script.
- `optionsInTargetFieldTest`: Ant options can be used in `Targets` field.
- `customBuildFileTest`: Can use a build file different from `build.xml`
- `unexistingCustomBuildFileTest`: If build file specified does not exist, build should fail.

@reviewbybees

### CODE REVIEW

**Comment by andresrc** [comment]
:bee:

**Comment by recena** [comment]
🐝

**Comment by armfergom** [comment]
@reviewbybees done

**Comment by armfergom** [comment]
Squashing commits. Waiting for CI job to succeed to merge.

**Pull request merged**
